var m_b5 = new Array("dummy","區","歐","歐陽","鮑","邦","陳","巢","周","鄒","瘳","鄭","卓","張","池","蔣","錢","戚","赤","秦","程","趙","肖","曹","蔡","朱","崔","祝","鍾","戴","謝","翟","奠","刁","范","樊","霍","方","鄺","傅","苻","馮","郟","甄","夏","侯","何","賀","譚","韓","康","項","候","禤","許","熊","洪","孔","詹","甘","金","簡","姜","揭","高","江","葛","古","顧","股","龔","關","郭","官","黎","賴","林","藍","劉","李","利","梁","連","練","凌","廖","盧","勞","羅","駱","洛","雷","呂","陸","龍","馬","麥","文","萬","孟","繆","巫","毛","武","莫","梅","閔","蒙","伍","吳","倪","魏","顏","敖","岳","寧","聶","柯","白","彭","包","龐","潘","盤","辛","司徒","施","石","佘","是","岑","淳","色","單","冼","成","薛","蕭","蘇","孫","沈","宋","談","覃","鄧","滕","禢","田","丁","杜","涂","湯","唐","曾","徐","衛","韋","溫","尹","屈","黃","王","胡","任","殷","丘","邱","余","楊","嚴","英","葉","姚","饒","茹","俞","阮","袁","遠","翁","容");
var m_rom = new Array("","Au","Au","Au Yeung","Bau, Pao","Bong","Chan, Chin","Chao","Chau, Chow","Chau, Chow","Chau","Cheng","Cheuk","Cheung","Chi","Chiang","Chien, Chin","Chik","Chik","Chin","Ching","Chiu, Chu, Jew","Chiu","Cho, Tso","Choi, Toy, Tsoi","Chu, Gee","Chui","Chuk","Chung","Dai, Tai","Der, Tse","Dik","Din","Diu","Fan","Fan","Fok","Fong","Fong, Kwong","Fu","Fu","Fung","Gap","Gin, Yan","Ha","Hau","Ho","Ho","Hom, Tam","Hon","Hong","Hong","Hou","Huen","Hui","Hung","Hung","Hung","Jim","Kam","Kam","Kan","Keung","Kit","Ko","Kong","Kot","Ku","Ku","Ku","Kung","Kwan","Kwok","Kwoon","Lai","Lai","Lam, Lum","Lam","Lau","Lee","Lee","Leung","Lin","Lin","Ling","Liu","Lo","Lo","Lo, Lor","Lok","Lok","Louie, Lui","Lui","Luk","Lung","Ma, Mar","Mak","Man, Mun","Man","Mang","Mau","Mo","Mo","Mo","Mok","Moy","Mun","Mung","Ng","Ng","Ngai","Ngai","Ngan","Ngo","Ngok","Ning","Nip","Or","Pak","Pang","Pao","Pong","Poon, Pun","Poon","San, Sun","Seto","She","Shek","Sher","Shi","Shum","Shun","Sik","Sin","Sin","Sing","Sit","Siu","So","Suen, Sun","Sum","Sung","Tam","Tam","Tang","Tang","Tap","Tin","Ting","To","To","Tong","Tong","Tsang","Tsui","Wai, Wei","Wai","Wan, Won","Wan","Wat","Wong","Wong","Woo, Wu","Yam","Yan","Yau","Yau","Yee, Yu","Yeung","Yim","Ying","Yip","Yiu","Yiu","Yu","Yu","Yuen","Yuen","Yuen","Yung","Yung");
var m_py = new Array("","Ōu","Ōu","Ōuyáng","Bào","Bāng","Chén","Cháo","Zhōu","Zōu","Chōu","Zhèng","Zhuó","Zhāng","Chí","Jiǎng","Qián","Qī","Chì","Qín","Chéng","Zhào","Xiào","Cáo","Cài","Zhū","Cuī","Zhù","Zhōng","Dài","Xiè","Dí","Diàn","Diāo","Fàn","Fán","Huò","Fāng","Kuàng","Fù","Fú","Féng","Jiá","Zhēn","Xià","Hóu","Hé","Hè","Tán","Hán","Kāng","Xiàng","Hòu","Xuān","Xǔ","Xióng","Hóng","Kǒng","Zhān","Gān","Jīn","Jiǎn","Jiāng","Jiē","Gāo","Jiāng","Gě","Gǔ","Gù","Gǔ","Gōng","Guān","Guō","Guān","Lí","Lài","Lín","Lán","Liú","Lǐ","Lì","Liáng","Lián","Liàn","Líng","Liào","Lú","Láo","Luó","Luò","Luò","Léi","Lǚ","Lù","Lóng","Mǎ","Mài","Wén","Wàn","Mèng","Móu","Wū","Máo","Wǔ","Mò","Méi","Mǐn","Méng","Wǔ","Wú","Ní","Wèi","Yán","Áo","Yuè","Níng","Niè","Kē","Bái","Péng","Bāo","Páng","Pān","Pán","Xīn","Sītú","Shī","Shí","Shé","Shì","Cén","Chún","Sè","Shàn","Shěng","Chéng","Xuē","Xiāo","Sū","Sūn","Chén","Sòng","Tán","Tán","Dèng","Téng","Tā","Tián","Dīng","Dù","Tú","Tāng","Táng","Zēng","Xú","Wèi","Wéi","Wēn","Yǐn","Qū","Huáng","Wáng","Hú","Rèn","Yīn","Qiū","Qiū","Yú","Yáng","Yán","Yīng","Yè","Yáo","Ráo","Rú","Yú","Ruǎn","Yuán","Yuǎn","Wēng","Róng");
function resetMenu() {
	var n = document.surname.surname.options; var s;
	var show_py = document.cookie.indexOf("&py") != -1;
	var sort_py = document.cookie.indexOf("sort=py") != -1;
	for (i=1; i<n.length; i++) {
		if (show_py) {
			if (sort_py) s = m_py[i] + ' (' + m_rom[i] + ')';
			else s = m_rom[i] + ' (' + m_py[i] + ')';
		} else s = m_rom[i];
		n[i].text = s + ' (' + m_b5[i] + ')';
	}
}
